# 수정한 부분에만 주석을 달아 표시해드렸습니다.

# Theme 설정 제거 (Chirpy 사용 중이므로 해당 항목 불필요)
# minimal_mistakes_skin    : "default"

# ------------------------
# ✅ Site Settings
# ------------------------
locale                   : "ko-KR"              # 수정: 한국어 설정

# 사이트 제목 및 설명
title                    : "HanksLog"           # 유지
subtitle                 : "Backend Developer"  # 추가: 사이트 부제
name                     : "Kyungsoo Han"       # 유지

# 사이트 설명
description              : "Java, Spring Boot 기반 백엔드 개발자"  # 수정

# 깃허브 주소 및 도메인 설정
url                      : "https://kyungsoo-han.github.io"
baseurl                  : ""                   # 수정: 루트 도메인이므로 공백
repository               : "kyungsoo-han/kyungsoo-han.github.io"

# 타임존 설정
timezone: Asia/Seoul                           # 유지

# ------------------------
# ✅ Author
# ------------------------
author:
  name             : "Kyungsoo Han"            # 수정
  avatar           : "/assets/images/profile.jpg"   # 예시 경로 (없다면 나중에 추가)
  bio              : "WMS / MES / Kafka / Redis 실무 기반 백엔드 개발자" # 수정
  location         : "Republic of Korea"
  email            : "hanks6160@gmail.com"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope"
      url: "mailto:hanks6160@gmail.com"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/KyungSoo-Han"
    - label: "Notion"
      icon: "fas fa-fw fa-book"
      url: "https://your-notion-link"  # 수정 필요 시 반영

# ------------------------
# ✅ Social (Footer 및 SEO)
# ------------------------
social:
  type                   : "Person"
  name                   : "Kyungsoo Han"
  links:
    - "https://github.com/kyungsoo-han"
    - "mailto:hanks6160@gmail.com"

footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/kyungsoo-han"
    - label: "Notion"
      icon: "fas fa-fw fa-book"
      url: "https://your-notion-link"  # 수정 필요 시 반영

# ------------------------
# ✅ Optional 기능 설정
# ------------------------
comments:
  provider: "utterances"         # 댓글 시스템 설정 (GitHub 기반)
  utterances:
    theme: "github-light"
    issue_term: "pathname"

google:
  search_engine_id:              # 필요 시 등록

search: true                     # 검색 기능 활성화
search_full_content: true

# ------------------------
# ✅ 기본 설정 유지
# ------------------------
markdown: kramdown
highlighter: rouge
excerpt_separator: "\n\n"
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

permalink: /:categories/:title/
paginate: 5

compress_html:
  clippings: all
  ignore:
    envs: development

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
