# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve`. If you change this file, please restart the server process.

# Theme Settings
# (Chirpy 사용 시에는 불필요하지만 주석 처리로 남겨둠)
# theme                  : "minimal-mistakes-jekyll"
# remote_theme           : "mmistakes/minimal-mistakes"
# minimal_mistakes_skin    : "default"

# Site Settings
locale                   : "ko-KR"
rtl                      : # true, false (default)
title                    : "HanksLog"
title_separator          : "-"
subtitle                 : "Backend Developer"
name                     : "Kyungsoo Han"
description              : "Java, Spring Boot 기반 백엔드 개발자"
url                      : "https://kyungsoo-han.github.io"
baseurl                  : ""  # 루트 도메인 사용 시 공백 유지
repository               : "kyungsoo-han/kyungsoo-han.github.io"
teaser                   : # "/assets/images/teaser.png"  # 필요 시 이미지 파일 추가
logo                     : # "/assets/images/logo.png"    # 필요 시 이미지 파일 추가
masthead_title           : " "  # 제목 제거 시 공백 설정
breadcrumbs              : false
words_per_minute         : 200
enable_copy_code_button  : true
copyright                : "Kyungsoo Han"
copyright_url            : "https://kyungsoo-han.github.io"
comments:
  provider               : "utterances"
  utterances:
    theme                : "github-light"
    issue_term           : "pathname"
reCaptcha:
  siteKey                :
  secret                 :
atom_feed:
  path                   :
  hide                   : false
search                   : true
search_full_content      : true
search_provider          : lunr
lunr:
  search_within_pages    : true
algolia:
  application_id         :
  index_name             :
  search_only_api_key    :
  powered_by             :
google:
  search_engine_id       :
  instant_search         : false

# SEO Related
google_site_verification :
bing_site_verification   :
naver_site_verification  :
yandex_site_verification :
baidu_site_verification  :

# Social Sharing
twitter:
  username               :
facebook:
  username               :
  app_id                 :
  publisher              :
og_image                 : # "/assets/images/og_image.png"  # 필요 시 이미지 파일 추가
social:
  type                   : "Person"
  name                   : "Kyungsoo Han"
  links:
    - "https://github.com/KyungSoo-Han"
    - "mailto:hanks6160@gmail.com"
    - "https://notion.site/your-notion"

# Analytics
analytics:
  provider               : false
  google:
    tracking_id          :
    anonymize_ip         : false

# Site Author
author:
  name             : "Kyungsoo Han"
  avatar           : # "/assets/images/profile.jpg"  # 프로필 이미지 준비 필요
  bio              : "백엔드 개발자"
  location         : # "Republic of Korea"
  email            : "hanks6160@gmail.com"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/KyungSoo-Han"
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:hanks6160@gmail.com"

# Site Footer
footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/KyungSoo-Han"
    - label: "Email"
      icon: "fas fa-fw fa-envelope"
      url: "mailto:hanks6160@gmail.com"

# Reading Files
include:
  - .htaccess
  - _pages
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - minimal-mistakes-jekyll.gemspec
  - node_modules
  - package.json
  - package-lock.json
  - Rakefile
  - README
  - tmp
  - /docs
  - /test
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed

# Outputting
permalink: /:categories/:title/
timezone: Asia/Seoul

# Pagination with jekyll-paginate
paginate: 5
paginate_path: /page:num/

# Pagination with jekyll-paginate-v2
pagination:
  debug: false
  collection: 'posts'
  per_page: 10
  permalink: '/page/:num/'
  title: ':title - page :num'
  limit: 0
  sort_field: 'date'
  sort_reverse: true
  category: 'posts'
  published: true
  tag: ''
  locale: ''
  trail:
    before: 2
    after: 2

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

# Archives
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# HTML Compression
compress_html:
  clippings: all
  ignore:
    envs: development

# Defaults
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
